
x-airflow-common: &airflow-common-env
  AIRFLOW__CORE__EXECUTOR: CeleryExecutor
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
  AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
  AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./postgres-init/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:latest

  airflow-webserver:
    image: airflow-custom:latest
    container_name: airflow-webserver
    depends_on:
      - postgres
      - redis
    environment:
      <<: *airflow-common-env
    command: webserver
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins

  airflow-scheduler:
    image: airflow-custom:latest
    container_name: airflow-scheduler
    depends_on:
      - airflow-webserver
    environment:
      <<: *airflow-common-env
    command: scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins

  airflow-worker:
    image: airflow-custom:latest
    container_name: airflow-worker
    depends_on:
      - airflow-webserver
    environment:
      <<: *airflow-common-env
    command: celery worker
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins

  airflow-init:
    image: airflow-custom:latest
    container_name: airflow-init
    depends_on:
      - postgres
      - redis
    environment:
      <<: *airflow-common-env
    entrypoint: /bin/bash
    command: -c "airflow db init && airflow users create --username admin --firstname admin --lastname admin --role Admin --email admin@example.com --password admin"

volumes:
  postgres-db-volume: